name: Validate and Auto Publish

on:
  push:
    branches:
      - gh-pages
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-20.04 # only linux supported at present
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2 # use the action
        with:
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          W3C_NOTIFICATIONS_CC: "dom@w3.org"
          VALIDATE_LINKS: false
          W3C_BUILD_OVERRIDE: |
            shortName: mediacapture-fromelement
            specStatus: WD
          
